miscellaneous cleanup
dhebbeker/task-tracker pull request #29
Opened 2023-05-13 18:54 UTC by dhebbeker

- Add feature to decode backtrace.  
  See [comment][1].  
  Do not forget to build in debug-mode. For example in PlatformIO IDE, select as project task 'Advanced' → 'Pre-Debug'. See also [here][2].  
  To decode backtraces from the Wokwi serial monitor, one can use [this python script][3].
- Move options which are only relevant for embedded, to specific environment.
- Delete settings where default values are OK.
- Added project description using PIO wizard.  
  Used the PIO IDE to configure project: Added project description.  
  Using the wizard did cleanup the file.
- Miscellaneous cleanup.
- Print detected event.

[1]: https://github.com/platformio/platform-espressif32/issues/105#issuecomment-945158769  
[2]: https://docs.platformio.org/en/latest/projectconf/build_configurations.html#build-configurations  
[3]: https://github.com/me21/EspArduinoExceptionDecoder

2023-05-22 19:39 UTC, FiveTeethless requested changes

2023-05-22 19:39 UTC, FiveTeethless commented on platformio.ini
> -src_dir = src
you can leave this out

2023-05-22 19:39 UTC, FiveTeethless commented on platformio.ini
> -include_dir = src
maybe check this, if it was necessary to stop PlatformIO from complaining, about missing "include" directory.

2023-05-22 19:39 UTC, FiveTeethless commented on platformio.ini
> -build_src_filter = +<*> -<.git/> -<.svn/>
you can leave this out

2023-05-22 19:39 UTC, FiveTeethless commented on platformio.ini
> -lib_deps =
this shoul be left here for other platforms

2023-05-22 19:39 UTC, FiveTeethless commented on platformio.ini
> -;;add dependencies to general dependencies from [env]
this is an example of how the config of [env] can be expanded. If "${env.lib_deps}" was not used, the parameter would be overwritten.

2023-05-22 19:43 UTC, dhebbeker reviewed
Todo:

- [ ] lib_deps to [env]
- [ ] check if include_dir is necessary
- [ ] leave comments

2023-05-27 20:40 UTC, dhebbeker commented
We have agreed, that most changes shall not be applied.

- Our comments shall be retained. They are generally useful. Too bad that PlatformIO deletes them (see platformio/platformio-core#3862). Using that tool requires to revert the deletion of comments.
- some options may be relevant or will be soon

I will rebase the remaining useful changes and create a new pull request.

2023-05-27 20:40 UTC, closed without merging